### ISSUE TITLE
MUK MSOffice Preview Error 

### ISSUE THREAD

**Issue by asolano88** [muk-it/muk_dms#87] opened 2019-05-21 05:16 UTC
When previewing MS Office (Word, PPT or Excel)

It will give an error on the Preview:

" An error occured
We're sorry, but for some reason we can't open this for you."

**Comment by keshrath** [comment] 2019-05-21 06:04
Is `muk_web_utils` up to date? https://github.com/muk-it/muk_web/commit/6ab318c0d216f37bd6579e2ca0657c3edac9a48e

**Comment by asolano88** [comment] 2019-05-21 06:10
Hi Mathias,

Yes, muk_web_utils is version 12.0.2.9.4

**Comment by keshrath** [comment] 2019-05-21 06:12
Since you open the ticket in the dms repo i guess you are trying to preview a dms file. To preview a office file the system creates a temporary attachment. Can you check if the mimetype of this attachment is correctly set.

**Comment by asolano88** [comment] 2019-05-21 06:22
Hi Mathias,

Here is the file info for your reference.

Name:
product.template (9).xls
Mimetype:
application/vnd.ms-excel
Size:
760.83 KB
Last Updated on:
2019-04-23 03:36:53
Last Updated by:
Administrator




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by keshrath** [comment] 2019-05-21 06:41
This is the dms file or the attachment?

**Comment by asolano88** [comment] 2019-05-21 06:56
DMS File.

It automatically creates the same Name as the attachment.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by keshrath** [comment] 2019-05-21 07:34
And this attachment has the right mimetype?

**Comment by keshrath** [comment] 2019-05-21 07:35
Just to make sure: You are trying to do that on a server right? not local with localhost? localhost wont work since the MS Office Viewer needs to be able to download the file, so it has to be available on the web.

**Comment by asolano88** [comment] 2019-05-21 07:39
Yes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by keshrath** [comment] 2019-05-21 07:47
I was able to reproduce it. Its a problem for non admin users. Admin seem to work fine.

I will close this ticket since its not a dms bug and reopen this one: 
https://github.com/muk-it/muk_web/issues/85

**Comment by asolano88** [comment] 2019-05-21 07:47
Hi Mathias,

The environment is that we have a local Server (on premise and with Odoo Community Edition v12). So is this the issue?

________________________________

**Closed as completed by keshrath** 2019-05-21 07:47 UTC
Labels: 12.0

**Comment by keshrath** [comment] 2019-05-21 07:51
On premise doesn't necessarily mean it's a problem. But the attachments have to be reachable via http/s. So if the server is completely in the VPN without access to the Internet, then it will not work.

**Comment by asolano88** [comment] 2019-05-21 07:56
Hi Mathias,

I understand.

At this time, our setup is without access to internet.

________________________________

**Comment by asolano88** [comment] 2019-06-15 03:25
Hi Mathias,

May I check with you if you did have a chance to look at this issue?

Thanks and best regards,
Allen


DMS ver 12- using Filter for the Field Tags #89
 Open
asolano88<https://github.com/asolano88> opened this issue 16 days ago · 0 comments
 Open
DMS ver 12- using Filter for the Field Tags<https://github.com/muk-it/muk_dms/issues/89> #89
asolano88<https://github.com/asolano88> opened this issue 16 days ago · 0 comments
Comments
Assignees
No one assigned
Labels
12.0<https://github.com/muk-it/muk_dms/labels/12.0>
Projects
None yet
Milestone
No milestone
Notifications
 Unsubscribe

You’re receiving notifications because you authored the thread.
2 participants
[@asolano88]<https://github.com/asolano88>[@keshrath]<https://github.com/keshrath>
[@asolano88]<https://github.com/asolano88>

asolano88<https://github.com/asolano88> commented 16 days ago<https://github.com/muk-it/muk_dms/issues/89#issue-450287763>

At the Files Menu:
Select Filters
Add Custom Filter
Select Field Tags condition (contains, not equal to , etc) = "value"

Error:
Odoo Server Error

Traceback (most recent call last):
File "/opt/odoo12/odoo/odoo/http.py", line 654, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo12/odoo/odoo/http.py", line 312, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/opt/odoo12/odoo/odoo/http.py", line 696, in dispatch
result = self._call_function(**self.params)
File "/opt/odoo12/odoo/odoo/http.py", line 344, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/opt/odoo12/odoo/odoo/http.py", line 337, in checked_call
result = self.endpoint(*a, **kw)
File "/opt/odoo12/odoo/odoo/http.py", line 939, in call
return self.method(*args, **kw)
File "/opt/odoo12/odoo/odoo/http.py", line 517, in response_wrap
response = f(*args, **kw)
File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 962, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/odoo12/odoo/odoo/api.py", line 745, in call_kw
return _call_kw_model(method, model, args, kwargs)
File "/opt/odoo12/odoo/odoo/api.py", line 718, in _call_kw_model
result = method(recs, *args, **kwargs)
File "/opt/odoo12/odoo-custom-addons/muk_dms/models/file.py", line 301, in search_panel_select_multi_range
return super(File, self).search_panel_select_multi_range(field_name, **kwargs)
File "/opt/odoo12/odoo-custom-addons/muk_web_searchpanel/models/base.py", line 132, in search_panel_select_multi_range
groups = self.read_group(model_domain, [field_name], [field_name])
File "/opt/odoo12/odoo/odoo/models.py", line 2070, in read_group
result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
File "/opt/odoo12/odoo/odoo/models.py", line 2093, in _read_group_raw
query = self._where_calc(domain)
File "/opt/odoo12/odoo/odoo/models.py", line 3879, in _where_calc
e = expression.expression(domain, self)
File "/opt/odoo12/odoo/odoo/osv/expression.py", line 672, in init
self.parse()
File "/opt/odoo12/odoo/odoo/osv/expression.py", line 1023, in parse
ids2 = [x[0] for x in comodel.name_search(right, domain or [], op2, limit=None)]
File "/opt/odoo12/odoo/odoo/models.py", line 1643, in name_search
return self._name_search(name, args, operator, limit=limit)
File "/opt/odoo12/odoo/odoo/models.py", line 1656, in _name_search
ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
File "/opt/odoo12/odoo/odoo/models.py", line 4083, in _search
if expression.is_false(self, args):
File "/opt/odoo12/odoo/odoo/osv/expression.py", line 225, in is_false
elif token[1] == 'in' and not token[2]:
IndexError: string index out of range

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
